import type { ContactStrings } from '../types';
import { site } from '../site';

export const contact: ContactStrings = {
  title: 'Contact and free 15-min call',
  description: 'Book a free 15-minute call or ask about a program, supervision or training – in English, German, Croatian or Spanish.',
  crumb: 'Contact',
  eyebrow: 'Contact',
  h1: 'Contact and *free 15-min call*',
  lead: `Tell me in a few sentences who you are, what it is about and which language you prefer. I reply ${site.contact.responseTime.en}.`,
  directTitle: 'Direct contact',
  area: 'Service area',
  noHealthTitle: 'Please do not send health data.',
  noHealth: 'This form deliberately does not ask for diagnoses, reports or details about your child\'s behavior. We discuss those confidentially in person.',
  nextTitle: 'What happens next',
  next: [
    'I read your message and reply personally.',
    'We arrange the free 15-minute video call.',
    'If it fits, you receive a written proposal – with no obligation.',
  ],
  formTitle: 'Send an enquiry',
  required: 'Required fields are marked *.',
  name: 'Name',
  email: 'Email',
  role: 'I am …',
  rolePlaceholder: 'Please choose',
  roles: {
    familie: 'A parent / family',
    fachkraft: 'A professional / supervision',
    institution: 'A Kita, school or organization',
    fortbildung: 'Asking about training or a talk',
    sprache: 'A multilingual family',
    sonstiges: 'Something else',
  },
  language: 'Preferred language',
  region: 'Town or region',
  optional: '(optional)',
  message: 'Short message',
  messageHint: 'For example: the program, format or timing you are interested in. Please no details about diagnoses, health or your child\'s behavior.',
  privacy: 'I have read the [privacy policy](@privacy). My details will only be used to handle my enquiry.',
  submit: 'Send enquiry',
  sending: 'Sending …',
  ok: '<strong>Thank you, your enquiry has arrived.</strong> I will get back to you personally.',
  err: '<strong>Your enquiry could not be sent.</strong> Please try again later or email me directly.',
  errors: {
    name: 'Please enter your name.',
    email: 'Please enter a valid email address.',
    role: 'Please choose who you are.',
    privacy: 'Please confirm that you have read the privacy policy.',
  },
  honeypot: 'Please leave empty',
  fallbackTitle: 'Enquiry by email',
  fallbackText: 'The contact form is not active yet. Please email me directly.',
  fallbackMail: 'Write an email',
  fallbackHint:
    'Please include your name, whether you are a parent, professional or organization, your region and your preferred language. We will discuss details about your child in person. See the [privacy policy](@privacy) for how your data is handled.',
  mailSubject: 'Enquiry via the website',
  mailBody: [
    'Name:',
    'I am: a parent / a professional / a Kita, school or organization / other',
    'Preferred language: English / Deutsch / Hrvatski / Español',
    'Region:',
    'What it is about, briefly (please no diagnoses or health details):',
    '',
  ],
  booking: 'Book online (external provider)',
  thanks: {
    title: 'Enquiry sent',
    description: 'Confirmation after sending the contact form.',
    crumb: 'Thank you',
    h1: 'Thank you for *your enquiry.*',
    lead: `Your message has arrived. I will reply ${site.contact.responseTime.en}.`,
    spam: 'If you do not hear back, please check your spam folder.',
    back: 'Back to the home page',
  },
};
