/**
 * Programs (research §3.3, prices §7.2 – proposals in site.ts until confirmed). One EUR price list for all languages.
 */
import type { Program, ProgramKey } from '../types';
import { site } from '../site';

const lang = 'English, German, Croatian, Spanish';

export const programs: Partial<Record<ProgramKey, Program>> = {
  fit: {
    name: 'Free 15-min call',
    for: 'For anyone who wants to find out whether my approach fits their situation.',
    includes: ['A short video call', 'An honest view on whether and how I can help', 'A recommendation for the right next step'],
    duration: '15 minutes',
    format: `Video · ${lang}`,
    price: 'free',
    cta: 'call',
  },
  clarity: {
    name: 'Clarity Consultation',
    for: 'For families who need an expert view and one clear next step.',
    includes: [
      'An in-depth conversation about your child, your daily life and your goals',
      'A first behavior-analytic view of what is going on',
      'A two-page written summary with concrete next steps',
    ],
    duration: '90 minutes + summary',
    format: `Online or in person · ${lang}`,
    price: 'clarity',
    cta: 'call',
  },
  assessment: {
    name: 'Behavior Assessment & Plan',
    for: 'For families who want to understand what is behind a behavior – with a plan everyone can use.',
    includes: [
      'A detailed intake interview following the PFA approach',
      'Two observations: at home, at Kita or school, or by video',
      'Review of all observations and existing reports',
      'A written support plan for family, Kita, school and school aide',
      'A handover session, with your child\'s team if you wish',
    ],
    duration: '3–4 weeks',
    format: `Online and/or in person · ${lang}`,
    price: 'assessment',
    cta: 'assessment',
    more: { label: 'What is a functional behavior assessment?', href: '@families#assessment' },
  },
  coaching: {
    name: 'Parent Coaching Program',
    for: 'For parents who want to put new approaches into practice, step by step, with support.',
    includes: [
      'Regular coaching sessions (online or in person)',
      'Ongoing plan updates',
      `Written check-ins between sessions, with a reply ${site.contact.responseTime.en}`,
      'Option: 12 instead of 8 weeks',
    ],
    duration: '8 weeks (12-week option)',
    format: `Online or in person · ${lang}`,
    price: 'coaching',
    cta: 'call',
    more: { label: 'What is parent coaching?', href: '@families#parent-coaching' },
  },
  toilet: {
    name: 'Focus Program "Toilet Training"',
    for: 'For families whose child is still in diapers at preschool or school age, or avoids the toilet.',
    includes: [
      'A look at readiness: communication, routines, sensory needs',
      'A step-by-step plan for home, Kita or school',
      'Weekly support and adjustments',
      'A pediatric check-up first (e.g. for constipation)',
    ],
    duration: '6 weeks',
    format: `Online or in person · ${lang}`,
    price: 'focus',
    cta: 'call',
    more: { label: 'More about toilet training', href: '@toilet' },
  },
  calmDays: {
    name: 'PFA-SBT Program "Calm Days"',
    for: 'For families whose days are shaped by meltdowns, hitting, biting or other challenging behavior.',
    includes: [
      'Assessment following the PFA approach',
      'A plan for more safety and calm in daily life',
      'Building communication and coping skills (SBT)',
      'Regular support, with Kita or school if you wish',
    ],
    duration: '8–12 weeks',
    format: `Online and in person · ${lang}`,
    price: 'calmDays',
    cta: 'call',
    more: { label: 'More about challenging behavior', href: '@behavior' },
  },
  firstSteps: {
    name: 'Focus Program "First Steps"',
    for: 'For families after an autism diagnosis – or while you wait for an assessment or a funded place.',
    includes: [
      'Sorting out what matters now and what can wait',
      'An overview of support, applications and where to go',
      'First practical steps for communication and routines',
      'A written 90-day plan',
    ],
    duration: '6 weeks',
    format: `Online or in person · ${lang}`,
    price: 'focus',
    cta: 'call',
    more: { label: 'More about first steps', href: '@diagnosis' },
  },
  intensive: {
    name: 'Home Intensive',
    for: 'For families who want fast, thorough progress – together with everyone who supports your child.',
    includes: [
      `2–3 days at your home – ${site.offer.travel}`,
      'Working with your family, school aide, Kita or school',
      'Assessment and a written plan',
      '6 weeks of remote follow-up',
    ],
    duration: '2–3 days + 6 weeks',
    format: `On site with you + online · ${lang}`,
    price: 'intensive',
    cta: 'call',
    flagship: true,
  },
  caseLead: {
    name: 'Ongoing Case Leadership',
    for: 'For families running a home program who need experienced clinical leadership.',
    includes: ['Three sessions per month', 'Supervision of the home program and its helpers', 'Coordination with Kita, school and therapists'],
    duration: 'monthly, cancelable',
    format: `Online and in person · ${lang}`,
    price: 'caseLead',
    cta: 'call',
  },
  navigation: {
    name: 'Expat Navigation',
    for: 'For international families finding their way through diagnosis, support, Kita and school in Germany.',
    includes: [
      'Overview: diagnosis pathway, Eingliederungshilfe, Kita, school, school aide',
      'Help putting documents together',
      'General information – not legal advice',
    ],
    duration: 'add-on to any program',
    format: 'Online · English, Croatian, Spanish, German',
    price: 'request',
    cta: 'call',
    more: { label: 'For expat families', href: '@expat' },
  },
  language: {
    name: 'Multilingual Family Consultation',
    for: 'For families who speak several languages and want to look at their child\'s behavior and communication together.',
    includes: [
      'A family language plan: who speaks which language, and when?',
      'Behavior-analytic ideas for everyday communication – in every family language',
      'A referral to a recognized speech therapy practice if needed',
    ],
    duration: 'by arrangement',
    format: `Online or in person · ${lang}`,
    price: 'request',
    cta: 'multilingual',
    more: { label: 'For multilingual families', href: '@multilingual' },
  },
  supIndividual: {
    name: 'Individual supervision',
    for: 'For professionals who want to reflect on their cases and their role on a regular basis.',
    includes: [
      'Case review with data and video (privacy-compliant)',
      'Ethics, assent and values in practice',
      'Case-based insight into PFA and SBT on request',
    ],
    duration: '60 minutes',
    format: 'Online · English, German, Croatian',
    price: 'supIndividual',
    cta: 'supervision',
  },
  supGroup: {
    name: 'Group supervision',
    for: 'For 3–6 professionals who want to learn from each other and build a shared language.',
    includes: ['Case work in a small group', 'A fixed group and rhythm', 'In English, German or Croatian'],
    duration: '90 minutes',
    format: 'Online · English, German, Croatian',
    price: 'supGroup',
    cta: 'supervision',
  },
  caseConsult: {
    name: 'Case consultation for teams, providers & youth welfare offices',
    for: 'For teams, service providers and youth welfare offices (Jugendamt) facing a stuck situation – and for new behavior analysts.',
    includes: ['One-off team case consultation', 'Mentoring for new professionals', 'A written recommendation if needed', site.checks.jugendamtRelease],
    duration: 'as needed',
    format: 'Online or in person',
    price: 'offer',
    cta: 'supervision',
  },
  training: {
    name: 'Team training (in-house)',
    for: 'For Kitas, schools, international schools and organizations.',
    includes: ['Topics and cases from your setting', 'Practical, with exercises', 'In English, German or Croatian', 'A handout to keep'],
    duration: 'half or full day',
    format: 'On site or online',
    price: 'trainingHalf',
    price2: { key: 'trainingFull', label: 'Full day' },
    cta: 'org',
  },
  talks: {
    name: 'Talks, keynotes & open workshops',
    for: 'For conferences, professional days, parent evenings and networks – plus open workshops for professionals.',
    includes: ['Keynote or interactive workshop', 'Topics: behavior, autism, multilingual families, an introduction to PFA and SBT', 'In English, German or Croatian'],
    duration: '45–60 minutes or half a day',
    format: 'On site or online',
    price: 'request',
    cta: 'talk',
  },
};
