import type { Ui } from '../types';

export const ui: Ui = {
  skip: 'Skip to content',
  menu: 'Menu',
  close: 'Close',
  navLabel: 'Main navigation',
  subnavToggle: 'Open submenu:',
  breadcrumbLabel: 'Breadcrumb',
  home: 'Home',
  langLabel: 'Language',
  langHomeHint: 'home page',
  nav: [
    {
      key: 'families',
      label: 'Families',
      children: [
        { key: 'families', label: 'Overview & programs' },
        { key: 'toilet' },
        { key: 'behavior' },
        { key: 'diagnosis' },
        { key: 'multilingual' },
        { key: 'expat' },
      ],
    },
    { key: 'professionals', label: 'Professionals' },
    { key: 'organizations', label: 'Schools & Organizations' },
    {
      key: 'about',
      label: 'About',
      children: [{ key: 'about', label: 'About Marija' }, { key: 'approach' }, { key: 'faq' }],
    },
    { key: 'pricing', label: 'Programs' },
  ],
  headerCta: 'Free 15-min call',
  cta: {
    call: 'Book a free 15-min call',
    assessment: 'Request an assessment',
    supervision: 'Ask about supervision',
    org: 'Request a training',
    meeting: 'Arrange a professional call',
    talk: 'Check availability',
    multilingual: 'Ask about multilingual support',
    question: 'Ask a question',
    pricing: 'Programs & fees',
  },
  trust: 'Confidential · no diagnosis · no emergency care',
  footer: {
    families: 'For families',
    more: 'More',
    contact: 'Contact',
    legal: 'Legal',
    disclaimer:
      'Consultation, coaching, supervision and training. No diagnosis, no psychotherapy, no emergency care. In an emergency in Germany call 112; out-of-hours doctor 116 117.',
    noCookies: 'This website sets no cookies and loads no third-party content.',
    samples: 'Sample images: the portraits are provisional and partly AI-generated. They will be replaced with real photos.',
    contactLink: 'Contact & free 15-min call',
    familyLinks: ['families', 'toilet', 'behavior', 'diagnosis', 'multilingual', 'expat'],
    moreLinks: ['professionals', 'organizations', 'about', 'approach', 'pricing', 'faq'],
  },
  photoAlt: {
    studio: 'Marija Vargas in a navy blazer against a grey studio background',
    berlin: 'Marija Vargas in a light blazer in front of a neoclassical building in the city',
    coast: 'Marija Vargas in a blue blazer in front of a coastal landscape',
    officeBeige: 'Marija Vargas smiling in a light blazer in a bright office',
    officeNavy: 'Marija Vargas smiling in a navy blazer in a bright office',
    corridorNavy: 'Marija Vargas in a navy blazer in a bright office corridor',
    duo: 'Marija Vargas and her sister, her partner for language and multilingual development, side by side in a bright office',
    duoBeige: 'Marija Vargas and her sister in light blazers in an office with large windows',
    realSmile: 'Marija Vargas laughing in front of a white brick wall',
    realGarden: 'Marija Vargas in a brown blouse in a garden under green leaves',
  },
  programs: {
    for: 'For',
    includes: 'Includes',
    duration: 'Duration',
    format: 'Format & languages',
    price: 'Fee',
    free: 'free',
    onRequest: 'Fees on request',
    offer: 'by quote',
    flagship: 'Flagship',
    from: (a) => `from €${a}`,
    perMonth: '/ month',
    perPerson: 'per person',
    plusTravel: '+ travel costs',
    plusVat: '+ VAT',
    more: 'Learn more',
  },
  author: {
    label: 'Author',
    updated: 'Last updated',
    role: 'Behavior consultation following PFA and SBT',
    link: 'About Marija',
  },
  faqMore: 'All questions and answers',
  numberLocale: 'en-US',
};
