import type { ContactStrings } from '../types';
import { site } from '../site';

// Native review by Marija needed.
export const contact: ContactStrings = {
  title: 'Kontakt i besplatan uvodni razgovor',
  description: 'Dogovorite besplatan uvodni razgovor od 15 minuta ili se raspitajte o programima i superviziji – na hrvatskom, njemačkom, engleskom ili španjolskom.',
  crumb: 'Kontakt',
  eyebrow: 'Kontakt',
  h1: 'Kontakt i *besplatan uvodni razgovor*',
  lead: `Napišite mi u nekoliko rečenica tko ste, o čemu je riječ i na kojem jeziku želite razgovarati. Odgovaram ${site.contact.responseTime.hr}.`,
  directTitle: 'Izravan kontakt',
  area: 'Područje rada',
  noHealthTitle: 'Molim bez zdravstvenih podataka.',
  noHealth: 'Ovaj obrazac namjerno ne traži dijagnoze, nalaze ni opis ponašanja Vašeg djeteta. O tome ćemo povjerljivo razgovarati osobno.',
  nextTitle: 'Kako dalje',
  next: ['Pročitam Vaš upit i osobno odgovorim.', 'Dogovorimo besplatan videorazgovor od 15 minuta.', 'Ako odgovara, dobit ćete pisanu ponudu – bez obveze.'],
  formTitle: 'Pošaljite upit',
  required: 'Obavezna polja označena su sa *.',
  name: 'Ime i prezime',
  email: 'E-pošta',
  role: 'Ja sam …',
  rolePlaceholder: 'Molim odaberite',
  roles: {
    familie: 'Roditelj / obitelj',
    fachkraft: 'Stručnjak / supervizija',
    institution: 'Vrtić, škola ili organizacija',
    fortbildung: 'Edukacija / predavanje',
    sprache: 'Višejezična obitelj',
    sonstiges: 'Ostalo',
  },
  language: 'Željeni jezik',
  region: 'Mjesto ili regija',
  optional: '(neobavezno)',
  message: 'Kratka poruka',
  messageHint: 'Na primjer: koji program, oblik ili termin Vas zanima. Molim bez podataka o dijagnozama, zdravlju ili ponašanju djeteta.',
  privacy: 'Pročitao/la sam [izjavu o privatnosti](@privacy). Moji podaci koristit će se samo za obradu upita.',
  submit: 'Pošalji upit',
  sending: 'Šaljem …',
  ok: '<strong>Hvala, Vaš je upit stigao.</strong> Javit ću Vam se osobno.',
  err: '<strong>Upit nije poslan.</strong> Molim pokušajte ponovno kasnije ili mi pišite izravno e-poštom.',
  errors: {
    name: 'Molim upišite svoje ime.',
    email: 'Molim upišite ispravnu adresu e-pošte.',
    role: 'Molim odaberite tko ste.',
    privacy: 'Molim potvrdite da ste pročitali izjavu o privatnosti.',
  },
  honeypot: 'Molim ostavite prazno',
  fallbackTitle: 'Upit e-poštom',
  fallbackText: 'Kontaktni obrazac još nije aktivan. Molim pišite mi izravno e-poštom.',
  fallbackMail: 'Napiši e-poruku',
  fallbackHint: 'Navedite ime, jeste li roditelj, stručnjak ili organizacija, regiju i željeni jezik. O djetetu ćemo razgovarati osobno. Više u [izjavi o privatnosti](@privacy).',
  mailSubject: 'Upit putem web-stranice',
  mailBody: ['Ime:', 'Ja sam: roditelj / stručnjak / vrtić, škola, organizacija / ostalo', 'Željeni jezik: hrvatski / Deutsch / English / Español', 'Regija:', 'Ukratko o čemu je riječ (bez dijagnoza i zdravstvenih podataka):', ''],
  booking: 'Online rezervacija (vanjski pružatelj)',
  thanks: {
    title: 'Upit poslan',
    description: 'Potvrda nakon slanja kontaktnog obrasca.',
    crumb: 'Hvala',
    h1: 'Hvala na *upitu.*',
    lead: `Vaša poruka je stigla. Odgovaram ${site.contact.responseTime.hr}.`,
    spam: 'Ako ne dobijete odgovor, provjerite i mapu neželjene pošte.',
    back: 'Na početnu stranicu',
  },
};
