import type { Ui } from '../types';

// Hrvatski: formalno „Vi“, ijekavica. Native review by Marija needed (vidi site/README.md).
export const ui: Ui = {
  skip: 'Preskoči na sadržaj',
  menu: 'Izbornik',
  close: 'Zatvori',
  navLabel: 'Glavna navigacija',
  subnavToggle: 'Otvori podizbornik:',
  breadcrumbLabel: 'Putanja',
  home: 'Početna',
  langLabel: 'Jezik',
  langHomeHint: 'početna stranica',
  nav: [
    {
      key: 'families',
      label: 'Obitelji',
      children: [{ key: 'families', label: 'Podrška obiteljima' }, { key: 'multilingual' }],
    },
    { key: 'professionals', label: 'Stručnjaci' },
    { key: 'about', label: 'O meni' },
    { key: 'pricing', label: 'Programi' },
  ],
  headerCta: 'Besplatan razgovor',
  cta: {
    call: 'Dogovorite besplatan uvodni razgovor',
    assessment: 'Zatražite procjenu',
    supervision: 'Upit za superviziju',
    org: 'Upit za edukaciju',
    meeting: 'Dogovorite stručni razgovor',
    talk: 'Provjerite dostupnost',
    multilingual: 'Upit za savjetovanje o višejezičnosti',
    question: 'Postavite pitanje',
    pricing: 'Programi i honorar',
  },
  trust: 'Povjerljivo · bez dijagnostike · bez hitne pomoći',
  footer: {
    families: 'Za obitelji',
    more: 'Ostale stranice',
    contact: 'Kontakt',
    legal: 'Pravne informacije',
    disclaimer:
      'Savjetovanje, coaching, supervizija i edukacija. Bez dijagnostike, bez psihoterapije, bez hitne pomoći. U hitnom slučaju nazovite 112 (u Njemačkoj dežurna liječnička služba: 116 117).',
    noCookies: 'Ova web-stranica ne koristi kolačiće i ne učitava sadržaje trećih strana.',
    samples: 'Ogledne fotografije: portreti su privremeni i dijelom generirani umjetnom inteligencijom. Bit će zamijenjeni stvarnim fotografijama.',
    contactLink: 'Kontakt i besplatan razgovor',
    familyLinks: ['families', 'multilingual'],
    moreLinks: ['professionals', 'about', 'pricing'],
  },
  photoAlt: {
    studio: 'Marija Vargas u tamnoplavom sakou ispred sive studijske pozadine',
    berlin: 'Marija Vargas u svijetlom sakou ispred klasicističke zgrade u gradu',
    coast: 'Marija Vargas u plavom sakou ispred obalnog krajolika',
    officeBeige: 'Marija Vargas nasmiješena, u svijetlom sakou, u svijetlom uredu',
    officeNavy: 'Marija Vargas nasmiješena, u tamnoplavom sakou, u svijetlom uredu',
    corridorNavy: 'Marija Vargas u tamnoplavom sakou u svijetlom hodniku ureda',
    duo: 'Marija Vargas i njezina sestra, partnerica za jezik i višejezičnost, jedna uz drugu u svijetlom uredu',
    duoBeige: 'Marija Vargas i njezina sestra u svijetlim sakoima u uredu s velikim prozorima',
    realSmile: 'Marija Vargas nasmijana ispred bijelog zida od opeke',
    realGarden: 'Marija Vargas u smeđoj bluzi u vrtu ispod zelenog lišća',
  },
  programs: {
    for: 'Za koga',
    includes: 'Uključeno',
    duration: 'Trajanje',
    format: 'Oblik i jezici',
    price: 'Honorar',
    free: 'besplatno',
    onRequest: 'Honorar na upit',
    offer: 'prema ponudi',
    flagship: 'Glavni program',
    from: (a) => `od ${a} €`,
    perMonth: '/ mjesečno',
    perPerson: 'po osobi',
    plusTravel: '+ putni troškovi',
    plusVat: '+ PDV',
    more: 'Saznajte više',
  },
  author: {
    label: 'Autorica',
    updated: 'Zadnje ažurirano',
    role: 'Savjetovanje prema pristupu PFA i SBT',
    link: 'O Mariji',
  },
  faqMore: 'Sva pitanja i odgovori',
  numberLocale: 'hr-HR',
};
