import type { ContactStrings } from '../types';
import { site } from '../site';

// Native review needed.
export const contact: ContactStrings = {
  title: 'Contacto y llamada gratuita',
  description: 'Reserve una llamada gratuita de 15 minutos o consulte sobre un programa – en español, inglés, alemán o croata.',
  crumb: 'Contacto',
  eyebrow: 'Contacto',
  h1: 'Contacto y *llamada gratuita*',
  lead: `Cuénteme en pocas frases quién es, de qué se trata y en qué idioma prefiere hablar. Respondo ${site.contact.responseTime.es}.`,
  directTitle: 'Contacto directo',
  area: 'Zona de trabajo',
  noHealthTitle: 'Por favor, sin datos de salud.',
  noHealth: 'Este formulario no pide diagnósticos, informes ni detalles sobre la conducta de su hijo o hija. Eso lo hablamos de forma confidencial en persona.',
  nextTitle: 'Próximos pasos',
  next: ['Leo su mensaje y respondo personalmente.', 'Acordamos la videollamada gratuita de 15 minutos.', 'Si encaja, recibe una propuesta por escrito, sin compromiso.'],
  formTitle: 'Enviar consulta',
  required: 'Los campos obligatorios están marcados con *.',
  name: 'Nombre',
  email: 'Correo electrónico',
  role: 'Soy …',
  rolePlaceholder: 'Elija una opción',
  roles: {
    familie: 'Madre, padre / familia',
    fachkraft: 'Profesional / supervisión',
    institution: 'Escuela u organización',
    fortbildung: 'Formación / charla',
    sprache: 'Familia bilingüe',
    sonstiges: 'Otro',
  },
  language: 'Idioma preferido',
  region: 'Ciudad o región',
  optional: '(opcional)',
  message: 'Mensaje breve',
  messageHint: 'Por ejemplo: el programa, formato o plazo que le interesa. Por favor, sin datos sobre diagnósticos, salud o conducta de su hijo o hija.',
  privacy: 'He leído la [política de privacidad](@privacy). Mis datos solo se usarán para atender mi consulta.',
  submit: 'Enviar consulta',
  sending: 'Enviando …',
  ok: '<strong>Gracias, su consulta ha llegado.</strong> Le responderé personalmente.',
  err: '<strong>No se ha podido enviar la consulta.</strong> Inténtelo más tarde o escríbame directamente por correo.',
  errors: {
    name: 'Indique su nombre, por favor.',
    email: 'Indique un correo electrónico válido, por favor.',
    role: 'Elija quién es, por favor.',
    privacy: 'Confirme que ha leído la política de privacidad, por favor.',
  },
  honeypot: 'Dejar en blanco',
  fallbackTitle: 'Consulta por correo electrónico',
  fallbackText: 'El formulario todavía no está activo. Escríbame directamente por correo, por favor.',
  fallbackMail: 'Escribir un correo',
  fallbackHint: 'Indique su nombre, si es familia, profesional u organización, su región y el idioma preferido. Los detalles sobre su hijo o hija los hablamos en persona. Más en la [política de privacidad](@privacy).',
  mailSubject: 'Consulta desde la web',
  mailBody: ['Nombre:', 'Soy: familia / profesional / escuela u organización / otro', 'Idioma preferido: Español / English / Deutsch / Hrvatski', 'Región:', 'Breve descripción (sin diagnósticos ni datos de salud):', ''],
  booking: 'Reservar online (proveedor externo)',
  thanks: {
    title: 'Consulta enviada',
    description: 'Confirmación tras enviar el formulario de contacto.',
    crumb: 'Gracias',
    h1: 'Gracias por *su consulta.*',
    lead: `Su mensaje ha llegado. Respondo ${site.contact.responseTime.es}.`,
    spam: 'Si no recibe respuesta, revise también la carpeta de correo no deseado.',
    back: 'Volver al inicio',
  },
};
