import type { Ui } from '../types';

// Español: trato de «usted», válido para España y Latinoamérica. Native review needed (ver site/README.md).
export const ui: Ui = {
  skip: 'Saltar al contenido',
  menu: 'Menú',
  close: 'Cerrar',
  navLabel: 'Navegación principal',
  subnavToggle: 'Abrir submenú:',
  breadcrumbLabel: 'Ruta de navegación',
  home: 'Inicio',
  langLabel: 'Idioma',
  langHomeHint: 'página de inicio',
  nav: [
    {
      key: 'families',
      label: 'Familias',
      children: [{ key: 'families', label: 'Asesoría para familias' }, { key: 'multilingual' }],
    },
    { key: 'about', label: 'Sobre mí' },
    { key: 'pricing', label: 'Programas' },
  ],
  headerCta: 'Llamada gratuita',
  cta: {
    call: 'Reserve una llamada gratuita de 15 minutos',
    assessment: 'Solicitar una evaluación',
    supervision: 'Consultar sobre supervisión',
    org: 'Solicitar una formación',
    meeting: 'Concertar una reunión profesional',
    talk: 'Consultar disponibilidad',
    multilingual: 'Consultar sobre bilingüismo',
    question: 'Hacer una pregunta',
    pricing: 'Programas y honorarios',
  },
  trust: 'Confidencial · sin diagnóstico · sin atención de urgencias',
  footer: {
    families: 'Para familias',
    more: 'Más páginas',
    contact: 'Contacto',
    legal: 'Información legal',
    disclaimer:
      'Asesoría, coaching, supervisión y formación. Sin diagnóstico, sin psicoterapia y sin atención de urgencias. En caso de emergencia llame al 112 (en Alemania, servicio médico de guardia: 116 117).',
    noCookies: 'Este sitio web no utiliza cookies ni carga contenidos de terceros.',
    samples: 'Imágenes de muestra: los retratos son provisionales y en parte generados con IA. Se sustituirán por fotos reales.',
    contactLink: 'Contacto y llamada gratuita',
    familyLinks: ['families', 'multilingual'],
    moreLinks: ['about', 'pricing'],
  },
  photoAlt: {
    studio: 'Marija Vargas con americana azul marino ante un fondo gris de estudio',
    berlin: 'Marija Vargas con americana clara ante un edificio neoclásico en la ciudad',
    coast: 'Marija Vargas con americana azul ante un paisaje costero',
    officeBeige: 'Marija Vargas sonriendo, con americana clara, en una oficina luminosa',
    officeNavy: 'Marija Vargas sonriendo, con americana azul marino, en una oficina luminosa',
    corridorNavy: 'Marija Vargas con americana azul marino en un pasillo de oficina luminoso',
    duo: 'Marija Vargas y su hermana, su socia para lenguaje y desarrollo multilingüe, una junto a la otra en una oficina luminosa',
    duoBeige: 'Marija Vargas y su hermana con americanas claras en una oficina con grandes ventanales',
    realSmile: 'Marija Vargas riendo ante una pared de ladrillo blanco',
    realGarden: 'Marija Vargas con blusa marrón en un jardín bajo hojas verdes',
  },
  programs: {
    for: 'Para quién',
    includes: 'Incluye',
    duration: 'Duración',
    format: 'Formato e idiomas',
    price: 'Honorarios',
    free: 'gratuita',
    onRequest: 'Honorarios a consultar',
    offer: 'según presupuesto',
    flagship: 'Programa insignia',
    from: (a) => `desde ${a} €`,
    perMonth: '/ mes',
    perPerson: 'por persona',
    plusTravel: '+ gastos de viaje',
    plusVat: '+ IVA',
    more: 'Más información',
  },
  author: {
    label: 'Autora',
    updated: 'Última actualización',
    role: 'Asesoría según el enfoque PFA y SBT',
    link: 'Sobre Marija',
  },
  faqMore: 'Todas las preguntas',
  numberLocale: 'es-ES',
};
