import type { ContactStrings } from '../types';
import { site } from '../site';

export const contact: ContactStrings = {
  title: 'Kontakt und kostenloses Kennenlernen',
  description:
    'Kostenloses 15-Minuten-Kennenlernen, Programm, Supervision oder Fortbildung anfragen – auf Deutsch, Englisch, Kroatisch oder Spanisch.',
  crumb: 'Kontakt',
  eyebrow: 'Kontakt',
  h1: 'Kontakt und *kostenloses Kennenlernen*',
  lead: `Schreiben Sie mir in wenigen Sätzen, wer Sie sind, worum es geht und in welcher Sprache Sie sprechen möchten. Ich antworte ${site.contact.responseTime.de}.`,
  directTitle: 'Direkter Kontakt',
  area: 'Einsatzgebiet',
  noHealthTitle: 'Bitte keine Gesundheitsdaten.',
  noHealth:
    'Dieses Formular fragt bewusst nicht nach Diagnosen, Befunden oder dem Verhalten Ihres Kindes. Solche Details besprechen wir vertraulich im Gespräch.',
  nextTitle: 'So geht es weiter',
  next: [
    'Ich lese Ihre Anfrage und antworte persönlich.',
    'Wir vereinbaren das kostenlose Kennenlernen (15 Minuten, per Video).',
    'Passt es, erhalten Sie ein schriftliches Angebot – ohne Verpflichtung.',
  ],
  formTitle: 'Anfrage senden',
  required: 'Pflichtfelder sind mit * markiert.',
  name: 'Name',
  email: 'E-Mail',
  role: 'Ich bin …',
  rolePlaceholder: 'Bitte auswählen',
  roles: {
    familie: 'Elternteil / Familie',
    fachkraft: 'Fachkraft / Supervision',
    institution: 'Kita, Schule oder Organisation',
    fortbildung: 'Fortbildung / Vortrag',
    sprache: 'Mehrsprachige Familie',
    sonstiges: 'Sonstiges',
  },
  language: 'Bevorzugte Sprache',
  region: 'Ort oder Region',
  optional: '(optional)',
  message: 'Kurze Nachricht',
  messageHint: 'Zum Beispiel: gewünschtes Programm, Format oder Zeitraum. Bitte keine Angaben zu Diagnosen, Gesundheit oder Verhalten Ihres Kindes.',
  privacy: 'Ich habe die [Datenschutzerklärung](@privacy) gelesen. Meine Angaben werden nur zur Bearbeitung meiner Anfrage verwendet.',
  submit: 'Anfrage senden',
  sending: 'Wird gesendet …',
  ok: '<strong>Danke, Ihre Anfrage ist angekommen.</strong> Ich melde mich persönlich bei Ihnen.',
  err: '<strong>Die Anfrage konnte nicht gesendet werden.</strong> Bitte versuchen Sie es später erneut oder schreiben Sie mir direkt eine E-Mail.',
  errors: {
    name: 'Bitte geben Sie Ihren Namen ein.',
    email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    role: 'Bitte wählen Sie aus, wer Sie sind.',
    privacy: 'Bitte bestätigen Sie, dass Sie die Datenschutzerklärung gelesen haben.',
  },
  honeypot: 'Bitte leer lassen',
  fallbackTitle: 'Anfrage per E-Mail',
  fallbackText: 'Das Kontaktformular ist noch nicht freigeschaltet. Bitte schreiben Sie mir direkt eine E-Mail.',
  fallbackMail: 'E-Mail schreiben',
  fallbackHint:
    'Bitte nennen Sie Ihren Namen, ob Sie Elternteil, Fachkraft oder Organisation sind, Ihre Region und Ihre bevorzugte Sprache. Details zu Ihrem Kind besprechen wir im Gespräch. Hinweise zur Verarbeitung Ihrer Angaben finden Sie in der [Datenschutzerklärung](@privacy).',
  mailSubject: 'Anfrage über die Website',
  mailBody: [
    'Name:',
    'Ich bin: Elternteil / Fachkraft / Kita, Schule, Organisation / Sonstiges',
    'Bevorzugte Sprache: Deutsch / English / Hrvatski / Español',
    'Region:',
    'Kurz, worum es geht (bitte keine Angaben zu Diagnosen oder Gesundheit):',
    '',
  ],
  booking: 'Termin online buchen (externer Anbieter)',
  thanks: {
    title: 'Anfrage gesendet',
    description: 'Bestätigung nach dem Absenden des Kontaktformulars.',
    crumb: 'Danke',
    h1: 'Danke für Ihre *Anfrage.*',
    lead: `Ihre Nachricht ist bei mir angekommen. Ich antworte ${site.contact.responseTime.de}.`,
    spam: 'Falls Sie keine Antwort erhalten, sehen Sie bitte auch im Spam-Ordner nach.',
    back: 'Zur Startseite',
  },
};
