/**
 * Programme (Research §3.3, Preise §7.2). Preise kommen aus site.ts → prices (Vorschläge, bis bestätigt).
 * Reihenfolge auf der Preisseite: vom Einstieg bis zum Flaggschiff.
 */
import type { Program, ProgramKey } from '../types';
import { site } from '../site';

const lang = 'Deutsch, Englisch, Kroatisch, Spanisch';

export const programs: Partial<Record<ProgramKey, Program>> = {
  fit: {
    name: 'Kostenloses Kennenlernen',
    for: 'Für alle, die klären möchten, ob mein Angebot zu ihrer Situation passt.',
    includes: ['Kurzes Gespräch per Video', 'Ehrliche Einschätzung, ob und wie ich helfen kann', 'Empfehlung für den passenden nächsten Schritt'],
    duration: '15 Minuten',
    format: `Video · ${lang}`,
    price: 'free',
    cta: 'call',
  },
  clarity: {
    name: 'Klarheitsgespräch',
    for: 'Für Familien, die eine fundierte Einschätzung und einen klaren nächsten Schritt brauchen.',
    includes: [
      'Ausführliches Gespräch über Ihr Kind, Ihren Alltag und Ihre Ziele',
      'Erste verhaltensanalytische Einordnung',
      'Schriftliche Zusammenfassung (2 Seiten) mit konkreten nächsten Schritten',
    ],
    duration: '90 Minuten + Zusammenfassung',
    format: `Online oder vor Ort · ${lang}`,
    price: 'clarity',
    cta: 'call',
  },
  assessment: {
    name: 'Verhaltensanalyse & Förderplan',
    for: 'Für Familien, die verstehen wollen, was hinter einem Verhalten steckt – mit einem Plan, den alle nutzen können.',
    includes: [
      'Ausführliches Aufnahmegespräch nach dem PFA-Ansatz',
      'Zwei Beobachtungen: zu Hause, in der Kita oder per Video',
      'Auswertung aller Beobachtungen und vorhandenen Berichte',
      'Schriftlicher Förderplan für Familie, Kita, Schule und Schulbegleitung',
      'Übergabegespräch, auf Wunsch mit dem Team Ihres Kindes',
    ],
    duration: '3–4 Wochen',
    format: `Online und/oder vor Ort · ${lang}`,
    price: 'assessment',
    cta: 'assessment',
    more: { label: 'Was ist eine funktionale Verhaltensanalyse?', href: '@families#verhaltensanalyse' },
  },
  coaching: {
    name: 'Elterncoaching-Programm',
    for: 'Für Eltern, die neue Wege im Alltag Schritt für Schritt umsetzen und dabei begleitet werden möchten.',
    includes: [
      'Regelmäßige Coaching-Termine (online oder vor Ort)',
      'Laufende Anpassung des Plans',
      `Schriftliche Check-ins zwischen den Terminen, Antwort ${site.contact.responseTime.de}`,
      'Option: 12 statt 8 Wochen',
    ],
    duration: '8 Wochen (Option 12 Wochen)',
    format: `Online oder vor Ort · ${lang}`,
    price: 'coaching',
    cta: 'call',
    more: { label: 'Was ist Elterncoaching?', href: '@families#elterncoaching' },
  },
  toilet: {
    name: 'Fokusprogramm „Sauber werden“',
    for: 'Für Familien, deren Kind im Kita- oder Schulalter noch Windeln trägt oder die Toilette meidet.',
    includes: [
      'Einschätzung der Voraussetzungen (Kommunikation, Routinen, Sinneswahrnehmung)',
      'Schritt-für-Schritt-Plan für zu Hause, Kita oder Schule',
      'Wöchentliche Begleitung und Anpassung',
      'Hinweis zur kinderärztlichen Abklärung vorab (z. B. Verstopfung)',
    ],
    duration: '6 Wochen',
    format: `Online oder vor Ort · ${lang}`,
    price: 'focus',
    cta: 'call',
    more: { label: 'Mehr zum Sauberwerden', href: '@toilet' },
  },
  calmDays: {
    name: 'PFA-SBT-Programm „Ruhigere Tage“',
    for: 'Für Familien, deren Alltag von Wutausbrüchen, Meltdowns, Schlagen oder Beißen geprägt ist.',
    includes: [
      'Verhaltensanalyse nach dem PFA-Ansatz',
      'Plan für mehr Sicherheit und Ruhe im Alltag',
      'Aufbau von Kommunikations- und Bewältigungsfähigkeiten (SBT)',
      'Regelmäßige Begleitung, auf Wunsch mit Kita oder Schule',
    ],
    duration: '8–12 Wochen',
    format: `Online und vor Ort · ${lang}`,
    price: 'calmDays',
    cta: 'call',
    more: { label: 'Mehr zu herausforderndem Verhalten', href: '@behavior' },
  },
  firstSteps: {
    name: 'Fokusprogramm „Erste Schritte“',
    for: 'Für Familien nach einer Autismus-Diagnose – oder während Sie auf Diagnostik oder einen Förderplatz warten.',
    includes: [
      'Sortieren: Was ist jetzt wichtig, was kann warten?',
      'Überblick über Hilfen, Anträge und Anlaufstellen',
      'Erste alltagsnahe Schritte für Kommunikation und Routinen',
      'Schriftlicher 90-Tage-Plan',
    ],
    duration: '6 Wochen',
    format: `Online oder vor Ort · ${lang}`,
    price: 'focus',
    cta: 'call',
    more: { label: 'Mehr zu den ersten Schritten', href: '@diagnosis' },
  },
  intensive: {
    name: 'Home Intensive',
    for: 'Für Familien, die schnell und gründlich vorankommen möchten – mit allen, die Ihr Kind begleiten.',
    includes: [
      `2–3 Tage bei Ihnen zu Hause – ${site.offer.travel}`,
      'Arbeit mit Familie, Schulbegleitung, Kita oder Schule',
      'Verhaltensanalyse und schriftlicher Plan',
      '6 Wochen Nachbetreuung online',
    ],
    duration: '2–3 Tage + 6 Wochen',
    format: `Vor Ort bei Ihnen + online · ${lang}`,
    price: 'intensive',
    cta: 'call',
    flagship: true,
  },
  caseLead: {
    name: 'Laufende Fallbegleitung',
    for: 'Für Familien mit einem Förderprogramm zu Hause, die eine erfahrene fachliche Leitung brauchen.',
    includes: [
      'Drei Termine pro Monat',
      'Supervision des häuslichen Programms und der Helfer:innen',
      'Abstimmung mit Kita, Schule und Therapien',
    ],
    duration: 'monatlich, kündbar',
    format: `Online und vor Ort · ${lang}`,
    price: 'caseLead',
    cta: 'call',
  },
  navigation: {
    name: 'Orientierung im deutschen System',
    for: 'Für internationale Familien, die sich in Diagnosewegen, Hilfen, Kita und Schule zurechtfinden möchten.',
    includes: [
      'Überblick: Diagnose, Eingliederungshilfe, Kita, Schule, Schulbegleitung',
      'Hilfe beim Zusammenstellen von Unterlagen',
      'Allgemeine Informationen – keine Rechtsberatung',
    ],
    duration: 'als Zusatz zu jedem Programm',
    format: 'Online · Englisch, Kroatisch, Spanisch, Deutsch',
    price: 'request',
    cta: 'call',
    more: { label: 'Für internationale Familien', href: '@expat' },
  },
  language: {
    name: 'Beratung für mehrsprachige Familien',
    for: 'Für Familien, in denen mehrere Sprachen gesprochen werden und die Verhalten und Kommunikation ihres Kindes zusammen betrachten möchten.',
    includes: [
      'Familien-Sprachplan: Wer spricht wann welche Sprache?',
      'Verhaltensanalytische Ideen für Kommunikation im Alltag – in jeder Familiensprache',
      'Bei Bedarf Empfehlung einer anerkannten logopädischen Praxis',
    ],
    duration: 'nach Absprache',
    format: `Online oder vor Ort · ${lang}`,
    price: 'request',
    cta: 'multilingual',
    more: { label: 'Mehr für mehrsprachige Familien', href: '@multilingual' },
  },
  supIndividual: {
    name: 'Einzelsupervision',
    for: 'Für Fachkräfte, die ihre Fälle und ihre Rolle regelmäßig reflektieren möchten.',
    includes: [
      'Fallbesprechung mit Daten und Videos (datenschutzkonform)',
      'Ethik, Assent und Haltung in der Praxis',
      'Auf Wunsch Praxiseinblick in PFA und SBT',
    ],
    duration: '60 Minuten',
    format: 'Online · Deutsch, Englisch, Kroatisch',
    price: 'supIndividual',
    cta: 'supervision',
  },
  supGroup: {
    name: 'Gruppensupervision',
    for: 'Für 3–6 Fachkräfte, die voneinander lernen und eine gemeinsame Sprache entwickeln wollen.',
    includes: ['Fallarbeit im kleinen Kreis', 'Feste Gruppe, fester Rhythmus', 'Deutsch, Englisch oder Kroatisch'],
    duration: '90 Minuten',
    format: 'Online · Deutsch, Englisch, Kroatisch',
    price: 'supGroup',
    cta: 'supervision',
  },
  caseConsult: {
    name: 'Fallberatung für Teams, Träger & Jugendämter',
    for: 'Für Teams, Träger und Jugendämter mit einer festgefahrenen Situation – und für Berufseinsteiger:innen in der Verhaltensanalyse.',
    includes: ['Punktuelle Fallberatung im Team', 'Mentoring für neue Fachkräfte', 'Auf Wunsch schriftliche Empfehlung', site.checks.jugendamtRelease],
    duration: 'nach Bedarf',
    format: 'Online oder vor Ort',
    price: 'offer',
    cta: 'supervision',
  },
  training: {
    name: 'Teamfortbildung (inhouse)',
    for: 'Für Kitas, Schulen, internationale Schulen und Träger.',
    includes: ['Thema und Fälle aus Ihrem Alltag', 'Praxisnah, mit Übungen', 'Auf Deutsch, Englisch oder Kroatisch', 'Handout zum Nachlesen'],
    duration: 'halber oder ganzer Tag',
    format: 'Vor Ort oder online',
    price: 'trainingHalf',
    price2: { key: 'trainingFull', label: 'Ganzer Tag' },
    cta: 'org',
  },
  talks: {
    name: 'Vorträge, Keynotes & offene Workshops',
    for: 'Für Fachtage, Konferenzen, Elternabende und Netzwerke – und offene Workshops für Fachkräfte.',
    includes: ['Keynote oder interaktiver Workshop', 'Themen: Verhalten, Autismus, Mehrsprachigkeit, Einführung in PFA und SBT', 'Auf Deutsch, Englisch oder Kroatisch'],
    duration: '45–60 Minuten oder halber Tag',
    format: 'Vor Ort oder online',
    price: 'request',
    cta: 'talk',
  },
};
