import type { Ui } from '../types';

export const ui: Ui = {
  skip: 'Zum Inhalt springen',
  menu: 'Menü',
  close: 'Schließen',
  navLabel: 'Hauptnavigation',
  subnavToggle: 'Untermenü öffnen:',
  breadcrumbLabel: 'Brotkrumen',
  home: 'Start',
  langLabel: 'Sprache',
  langHomeHint: 'Startseite',
  nav: [
    {
      key: 'families',
      label: 'Familien',
      children: [
        { key: 'families', label: 'Überblick & Programme' },
        { key: 'toilet' },
        { key: 'behavior' },
        { key: 'diagnosis' },
        { key: 'multilingual' },
        { key: 'expat' },
      ],
    },
    { key: 'professionals', label: 'Fachkräfte' },
    { key: 'organizations', label: 'Kitas & Schulen' },
    {
      key: 'about',
      label: 'Über mich',
      children: [{ key: 'about', label: 'Über Marija' }, { key: 'approach' }, { key: 'faq' }],
    },
    { key: 'pricing', label: 'Programme' },
  ],
  headerCta: 'Kostenloses Kennenlernen',
  cta: {
    call: 'Kostenloses Kennenlernen buchen',
    assessment: 'Verhaltensanalyse anfragen',
    supervision: 'Supervision anfragen',
    org: 'Fortbildung anfragen',
    meeting: 'Fachgespräch vereinbaren',
    talk: 'Verfügbarkeit anfragen',
    multilingual: 'Mehrsprachigkeits-Beratung anfragen',
    question: 'Frage stellen',
    pricing: 'Programme & Honorar',
  },
  trust: 'Vertraulich · keine Diagnostik · keine Notfallversorgung',
  footer: {
    families: 'Für Familien',
    more: 'Weitere Seiten',
    contact: 'Kontakt',
    legal: 'Rechtliches',
    disclaimer:
      'Beratung, Coaching, Supervision und Fortbildung. Keine Diagnostik, keine Psychotherapie, keine Notfallversorgung. Im Notfall: 112, ärztlicher Bereitschaftsdienst 116 117.',
    noCookies: 'Diese Website setzt keine Cookies und lädt keine Inhalte von Drittanbietern.',
    samples: 'Beispielbilder: Die Porträts sind vorläufig und teils KI-generiert. Sie werden durch echte Fotos ersetzt.',
    contactLink: 'Kontakt & kostenloses Kennenlernen',
    familyLinks: ['families', 'toilet', 'behavior', 'diagnosis', 'multilingual', 'expat'],
    moreLinks: ['professionals', 'organizations', 'about', 'approach', 'pricing', 'faq'],
  },
  photoAlt: {
    studio: 'Marija Vargas im dunkelblauen Blazer vor grauem Studiohintergrund',
    berlin: 'Marija Vargas im hellen Blazer vor einem klassizistischen Gebäude in der Stadt',
    coast: 'Marija Vargas im blauen Blazer vor einer Küstenlandschaft',
    officeBeige: 'Marija Vargas lächelnd im hellen Blazer in einem lichtdurchfluteten Büro',
    officeNavy: 'Marija Vargas lächelnd im dunkelblauen Blazer in einem hellen Büro',
    corridorNavy: 'Marija Vargas im dunkelblauen Blazer in einem hellen Büroflur',
    duo: 'Marija Vargas und ihre Schwester, Partnerin für Sprache und Mehrsprachigkeit, nebeneinander in einem hellen Büro',
    duoBeige: 'Marija Vargas und ihre Schwester in hellen Blazern in einem Büro mit großen Fenstern',
    realSmile: 'Marija Vargas lachend vor einer weißen Backsteinwand',
    realGarden: 'Marija Vargas in brauner Bluse im Garten unter grünem Laub',
  },
  programs: {
    for: 'Für wen',
    includes: 'Enthalten',
    duration: 'Dauer',
    format: 'Format & Sprachen',
    price: 'Honorar',
    free: 'kostenlos',
    onRequest: 'Honorar auf Anfrage',
    offer: 'nach Angebot',
    flagship: 'Flaggschiff',
    from: (a) => `ab ${a} €`,
    perMonth: '/ Monat',
    perPerson: 'pro Person',
    plusTravel: 'zzgl. Reisekosten',
    plusVat: 'zzgl. USt.',
    more: 'Mehr dazu',
  },
  author: {
    label: 'Autorin',
    updated: 'Zuletzt aktualisiert',
    role: 'Verhaltensanalytische Beratung nach PFA und SBT',
    link: 'Über Marija',
  },
  faqMore: 'Alle Fragen und Antworten',
  numberLocale: 'de-DE',
};
